name: C/C++ CI 

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
          
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        repository: ifsnop/reader_network
        path: main   

    - name: generate
      run: |
            cd /home/runner/work/reader_network/reader_network/main
            ./build.sh
            ls -la bin/
            
    - uses: actions/upload-artifact@v1
      with:
          name: artifact
          path: main/bin/
