name: C/C++ CI x86

on: [push]

jobs:
  build:

    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}    
    env:
      MSYS2_ARCH: i686
    steps:
    - uses: actions/checkout@v2
      with:
        repository: ifsnop/reader_network
        path: main      
      
    - uses: eine/setup-msys2@v1      
      with:
        update: true
        msystem: MINGW32
                
    - name: Install MSYS2 Dependencies
      run:  msys2do pacman --noconfirm -S --needed mingw-w64-i686-gcc mingw-w64-i686-crt make

    - name: make
      run: |
        cd main
        ./build.sh
